### PR TITLE
Added support for SYSS

### PR DESCRIPTION
**Pull request by sy9398**
- Added button for quick input on [SYSS, 12:55], and [SJACS, 12:05]
- Partially adopted Bootstrap style for the [Place] and [Time] input
- TODO: Place and time preference to be stored in localStorage

### CODE REVIEW

**Comment by jacky2001114** [comment]
Nice!
Welcome to become a contributor!

**Comment by sy9398** [comment]
This is a great platform for generating lunch order messages! I learnt this platform from my schoolmates 😂

**Comment by jacky2001114** [comment]
I am F6 too lol
Therefore i may not do any update for this web app
I would do the last update after 2019 DSE

**Comment by sy9398** [comment]
Gayau together la💪💪

**Pull request merged**
